name: development
channels:
  - conda-forge
  - defaults
dependencies:
    # base
  - python>=3.9
  - pip
  - numpy
  - scipy
  - pandas
  - geopandas
  - pygeos
  - pandana
  - osmdatapy
  - netpandas

    # development
  - ipykernel
  - black

    # testing
  - pytest
  - pytest-cov
  - codecov

    # Pip-only installs
  #- pip:
  #  - codecov

